### PR TITLE
onerror will now trigger a callback function if passed through in the options

### PR DESCRIPTION
**Pull request by MrSuttonmann**

### CODE REVIEW

**Comment by Archelyst** [comment]
Thank you. It's in line with the other callbacks. However, it also forces to specify the error callback and thus breaks bc. It'd be awesome if all callbacks could be optional. That's probably another ticket, though.

**Comment by PowerKiKi** [comment]
Indeed, please make the callback optional and then I could merge (and squash all commits into one)

**Comment by MrSuttonmann** [comment]
Hi, that should be enough to make the callback optional. If the callback is not a function it won't attempt to run it.

**Comment by Archelyst** [comment]
Awesome :)

**Comment by MrSuttonmann** [comment]
Welp, I'm not sure if I did that squash right.

**Comment by PowerKiKi** [comment]
Indeed there's quite a lot of commits, I think this should help you reduce your branch to a single commit: http://stackoverflow.com/questions/25356810/git-how-to-squash-all-commits-on-branch/25357146#25357146

**Comment by MrSuttonmann** [comment]
I messed up the branch. I'll close this PR and create a new one with a new branch with one commit.

**Pull request closed without merging**
